@base_url = http://localhost:5200
@authToken ={{authenticate.response.body.access_token}}

# @name create_account
POST {{base_url}}/accounts
Content-Type: application/json

{
  "name": "Jonas Mascarenhas",
  "email": "jonas.mascarenhas@gmail.com",
  "password": "Senha@123"
}

### 

# @name authenticate

POST {{base_url}}/sessions
Content-Type: application/json

{
  "email": "jonas.mascarenhas@gmail.com",
  "password": "Senha@123"
}

###


# @name create_qustion
POST {{base_url}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "nova pergunta maneira 3",
  "content": "conteudo da nova pergunta maneira"
}

###


# @name fetch_recent_questions
Get {{base_url}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}



